/*
 * Copyright (c) 2021 MegaEase
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.megaease.easeagent.plugin.interceptor;

import com.megaease.easeagent.plugin.Ordered;
import com.megaease.easeagent.plugin.api.Context;
import com.megaease.easeagent.plugin.api.config.IPluginConfig;
import com.megaease.easeagent.plugin.enums.Order;
import com.megaease.easeagent.plugin.interceptor.MethodInfo;

/**
 * 拦截器，这是 easeagent 插件的核心自定义逻辑，用户在其中可以自定义逻辑，支持 init -> before -> after 三个阶段
 *
 * - init 在首次
 */
public interface Interceptor extends Ordered {
    /**
     * 在方法执行之前触发的逻辑
     *
     * @param methodInfo instrumented method info 已增强的方法信息
     * @param context    Interceptor can pass data, method `after` of interceptor can receive context data 上下文
     */
    void before(MethodInfo methodInfo, Context context);

    /**
     * 在方法执行之后触发的逻辑
     *
     * @param methodInfo instrumented method info 已增器的方法信息
     * @param context    Interceptor can pass data, method `after` of interceptor can receive context data 上下文
     */
    default void after(MethodInfo methodInfo, Context context) {
    };

    /**
     * Interceptor can get interceptor config thought Config API :
     * EaseAgent.configFactory.getConfig
     * Config API require 3 params: domain, nameSpace, name
     * domain and namespace are defined by plugin, the third param, name is defined here
     *
     * @return name, eg. tracing, metric, etc.
     */
    default String getType() {
        return Order.TRACING.getName();
    }

    /**
     * 拦截器的初始化方法
     *
     * 对于每一个被这个拦截器注入的方法，这个方法会被调用一次，并且只会被调用一次
     * 这意味着，当存在多个匹配的方法时，该方法会被调用多次
     *
     * Initialization method for the interceptor,
     * This method will be called and only be called once for every method which is injected by this interceptor,
     * which means this method may be called several times, when there are several methods matched
     *
     * @param config interceptor configuration
     * @param className injected method's class name
     * @param methodName injected method name
     * @param methodDescriptor injected method descriptor
     */
    default void init(IPluginConfig config, String className, String methodName, String methodDescriptor) {
    }

    /**
     * 拦截器的初始化方法
     *
     * Initialization method for the interceptor,
     * This method will be called and only be called once for every method which is injected by this interceptor,
     * which means this method may be called several times, when there are several methods matched
     *
     * @param config    interceptor configuration
     * @param uniqueIndex an Integer unique index generated by agent
     *                    for each combination of className, method and methodDescriptor
     */
    default void init(IPluginConfig config, int uniqueIndex) {
    }
}
